### ISSUE TITLE
Two suggestions :)

### ISSUE THREAD

**Issue by ghost** [rock-hopper/shuriken#3]
Hello!

I have two suggestions for Shuriken :)
The first one is the classic "Open Recent..." in the file menu.
The second one is more technical, snap to zero crossing. We already have the possibility to snap to various note length in Shuriken and this could be another snapping option. 
One issue when working with audio files is that it is quite easy to make them produce an audible clic if they are not carefully trimmed at the start or end. An easy way to deal with this is to make them begin and end at the same sample value, usually zero. That is why finding zero-crossings is a common task done when working audio files into samples as it eases this process. This could be done this way:
If two consecutive samples make the wave cross the zero value (one of them has a positive value, the other a negative one), snap the slice point to the one who as the lowest absolute value.
Optionally, set the sample value where the slice point is positioned to 0 for a perfect transition/loop.

Best regards,
Barbouze

**Comment by rock-hopper** [comment]
Good suggestions. Quite a few people have asked about adding zero-crossing detection to Shuriken. I started on it today and it seems to be working nicely. I'm also adding context menus to the slice points to allow users to move them to the next/previous zero-crossing. Will hopefully get that finished off next weekend.

**Comment by rock-hopper** [comment]
OK, zero-crossing detection done!

**Comment by ghost** [comment]
Thanks a lot, it's a really fine feature :)
I read your comment on the problem with displaying perfectly waveform/slice point but for the now, as long as it is correctly positioned, everything is fine for me :)
I know that for the now you are polishing features but would there be a way to add keyboard shortcuts to move the selected slice point to previous or next zero-crossing?

**Comment by rock-hopper** [comment]
Keyboard shortcuts added (N and P) and Recent Projects menu now added too! Also, I was mistaken that there was an issue with the waveform not being drawn accurately. The problem was that when zoomed in to sample detail level the values of each sample are plotted about 1cm apart and the line joining the values sometimes crosses the center line between samples. It's therefore sometimes impossible for the slice point to be placed exactly where the waveform crosses the center line. I've now made the slice points snap to where the samples are plotted when zoomed in.

**Comment by ghost** [comment]
Well, everything is running fine here, and I love the slice points snapping to samples :)
Thanks a lot!
